apiVersion: v1
kind: ConfigMap
metadata:
  name: signer-config
  namespace: signer
data:
  CHAIN_ID: "11155111"
  AMOUNT_ETH: "0.001"
  TO_ADDRESS: "0xCHANGE_ME"
  KMS_KEY_ID: "arn:aws:kms:eu-west-1:905418421784:key/241cab65-63b1-4f3a-9002-0bc6b8ee4582"
