apiVersion: batch/v1
kind: Job
metadata:
  name: signer
  namespace: signer
spec:
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never
      serviceAccountName: eth-signer
      imagePullSecrets:
        - name: regcred
      containers:
      - name: app
        image: docker.io/flentier/eth-go-signer:latest
        env:
        - name: TO_ADDRESS
          valueFrom:
            configMapKeyRef:
              name: signer-config
              key: TO_ADDRESS
        - name: AMOUNT_ETH
          valueFrom:
            configMapKeyRef:
              name: signer-config
              key: AMOUNT_ETH
        - name: CHAIN_ID
          valueFrom:
            configMapKeyRef:
              name: signer-config
              key: CHAIN_ID
        - name: KMS_KEY_ID
          valueFrom:
            configMapKeyRef:
              name: signer-config
              key: KMS_KEY_ID
        - name: RPC_URL
          valueFrom:
            secretKeyRef:
              name: rpcurl
              key: RPC_URL
