apiVersion: v1
kind: Secret
metadata:
    name: rpcurl
    namespace: signer
type: Opaque
stringData:
    RPC_URL: ENC[AES256_GCM,data:4B4XgIBIrj6ABwJpuWP5r2Zb0QoB+LErX2covO8jbO2uEtCDB9IhYaPbs/Ch2OnFKEWGMxYlyjJEgWtNwDKuwKqaTYfhuJRIbqzSxfTsguptKXh3cEP89BeWXvrOkCQigo/evmztNKqb3LKKPlOGP+sViB3yMi5Zj+cw7F04Pmw/MQfebckANw4=,iv:VId9dpRr0tlctHbO0Xv0ozGXb0MqFJSeDGPSjU8zRa8=,tag:M7TFvFcxCKGbg2xHVGBZ+g==,type:str]
sops:
    age:
        - recipient: age1ne7zy5glnchpx0lc4usxkgexhrkyk43r93gyes4xx2d3wmwufdys0eqlrz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJcUJtcjZ0LzdORXhESW1I
            eVdCQXZTcXB6ZXVFdDdueHZRWHhCa1lPZXdVCnRBalNYSkxQd055bkNMUXNwTFc4
            Y21UVGVHRVNYZ1ZOaDc3NDZremRYanMKLS0tIFRrUy9nSWNTOEx2NTNoSUFjbTVP
            YVY5VUVXdWtNYVY0ZWZjajk0L3dIM2cKLwfH1z48T9U/vTGiDPNOdUYgLxc+TUlH
            CT5XTHDBSP8AZIlEJqRngklk8I25o1fBaie6VbKjgFRoYyCH9PVvwQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-17T13:24:12Z"
    mac: ENC[AES256_GCM,data:8enwJm7ehwi1BxjIJduKr6ETTLlsj0J323lxiUqWwA/ef3KfdTAqoW8PBfXaI66VmaUtd92GhbqdBBrxcVv8CoqLgMD3zH5yZO5PVTRc8aQeebXdO3BKMKSpc/eZHo1HARPoB2dN6U6HsZECQGFA/vtpRGp29UIq6PP99J283m4=,iv:jCSR5KU20JddD0cLu+83pH3e/835RgAbuKWLtfct8n0=,tag:rHmf+hSntxaaw/ixLnAKpg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
