apiVersion: v1
kind: Secret
metadata:
    name: regcred
    namespace: signer
type: kubernetes.io/dockerconfigjson
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:PlDZ49QW9OjPjwk8iLRz7Y0PTXHBtD5gWvEZBr/bluQ7aprXMJhDyRHy+Zor1GPgMe7fCM52VKabhLSqO8W273cepD13J35kwmSqEILxlhAKCVafZH57JO3Vvf6hFtSYTfPYV7SbGAWnerQHD66s9vsZ6kXMQtxgqUbmPxpi3qBGVwrCie/77qsgbQ6k4e1Zfye2rLAWLOokfax6NY/LqQF2Ltz2UACtUXRzi0Q6cb/WkM4js/4X6GXeuKZ7ygmFIvjFsfp8GiS+b5h2gBPJSWWUJYsU/AYEukKCtyH/1tCjnSBTTgE=,iv:Z1Vs+nUl8S7hLRyvtsHIu8FImOJE3/NxqOXPjbFlktI=,tag:HJuq5sqhwsyIVKMe7nKQUw==,type:str]
sops:
    age:
        - recipient: age1ne7zy5glnchpx0lc4usxkgexhrkyk43r93gyes4xx2d3wmwufdys0eqlrz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIMU5UVEZCMDJPMUJ1OUxO
            aXloVGtvZG5KV1dCdTh2MXllQk53czBjZ0EwCmNjWVduaXlWeS9GZWluVXRPSFVE
            UVQ5TFpwdkhySUNKVzlGRUVWTFhxUUUKLS0tIHBNYTJQTnhsTnhDVEgwam9XT0Y3
            QVJjYkl4RThLZmJDb3JhQUVaRW5zaHMKbY+D3sdy1ijovkhpGmKjPh9wgHyAb1be
            8QxNW2U83GFp20Kh2gox2NLDCpiUTgZMl7DAsaQS8zYMhKLIQHLq6A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-17T13:24:18Z"
    mac: ENC[AES256_GCM,data:aM+Ljn2lDQwvz0y4KA+kC0NmlPO6oaEtDAP6WITqW3pZ9+idurXSZDj91KlWkd0wwU2ECDrUqEj/irXh78pPAgXs89SBgThCrgPK+khBIMaZepixYVYgf+T5VRZmHAKHs0zaYhlUn39loN8BwqagdHXyZL2+/BFVuTZvV21ruKg=,iv:stsK0bMniCl4NvVXttzbcIGhiRGdcsdHn5D5WEijR0o=,tag:UgHWsQKIsdfhxV8DEhtWTA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
