name: CD
on:
  push:
    branches: [ placeholder ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure AWS creds
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Terraform Apply
        working-directory: terraform/root
        run: terraform init && terraform apply -auto-approve -var-file=../envs/dev/dev.tfvars
      - name: Update kubeconfig
        run: aws eks update-kubeconfig --name <cluster-name> --region $AWS_REGION
      - name: Deploy with Kustomize + SOPS
        env:
          AGE_SECRET_KEY: ${{ secrets.AGE_SECRET_KEY }}
        run: |
          kustomize build k8s/overlays/dev | sops -d /dev/stdin | kubectl apply -f -
